### ISSUE TITLE
documentation: definition of significance seems to be wrong

### ISSUE THREAD

**Issue by fookatchu** [nrc-cnrc/MetroloPy#23]
The definition of "significance" seems to be wrong. According to the docs:

> “s” or “significance”: the sensitivity coefficient (below) multiplied by the standard uncertainty, displayed by default

The significance is in fact calculated as `x.u / result.u` (or `v[0]/yu` in budget.py)

If I am not mistaken, the correct text should therefore be:

> “s” or “significance”: the sensitivity coefficient (below) multiplied by the standard uncertainty divided by the combined standard uncertainty, displayed by default

**Comment by fookatchu** [comment]
This also raises the question on how to retreive the uncertainty contribution `sensitivity coefficient * standard uncertainty`. Maybe I am just overlooking something?

**Comment by hvparks** [comment]
You are correct, the significance is sensitivity coefficient * standard uncertainty/combined uncertainty.

I will add a column for sensitivity coefficient * standard uncertainty

**Comment by hvparks** [comment]
The documentation has been fixed, though I still need to add the column for sensitivity coefficient * standard uncertainty.

**Comment by daharn** [comment]
The documentation is still wrong here. Moreover, wouldn't it make more sense to define `s` as `(sensitivity coefficient * standard uncertainty/combined uncertainty)**2` so they all add up to one?

**Comment by hvparks** [comment]
Significance is now (sensitivity coefficient * standard uncertainty/combined uncertainty)**2 in version 1 as you suggested
